spring:
  # 配置说明地址 https://shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-jdbc/configuration/config-spring-boot/#%E6%95%B0%E6%8D%AE%E5%88%86%E7%89%87
  shardingsphere:
    # 数据库
    datasource:
      # 数据库的别名
      names: ds0,ds1,ds2
      # 主库1 ,master数据库
      ds0:
        ###  数据源类别
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/master?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
        username: root
        password: root
      # 从库1 ,slave数据库
      ds1:
        ###  数据源类别
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/slaver1?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
        username: root
        password: root
      # 从库2 ,slave数据库
      ds2:
        ###  数据源类别
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/slaver2?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
        username: root
        password: root

    # *** 数据库分库分表配置 start
    masterslave:
      # 查询时的负载均衡算法，目前有2种算法，round_robin（轮询）和random（随机），
      # 算法接口是io.shardingjdbc.core.api.algorithm.masterslave.MasterSlaveLoadBalanceAlgorithm。
      # 实现类有RandomMasterSlaveLoadBalanceAlgorithm 和 RoundRobinMasterSlaveLoadBalanceAlgorithm。
      load-balance-algorithm-type: round_robin
      name: dataSource
      # 主数据源名称
      master-data-source-name: ds0
      # 从数据源名称，多个用逗号隔开
      slave-data-source-names: ds1,ds2
      # *** 数据库分库分表配置 end

    props:
      # 打印SQL
      sql.show: true
      check:
        table:
          metadata: true
          # 是否在启动时检查分表元数据一致性
          enabled: true

mybatis-plus:
  type-aliases-package: com.homework.sat03.mapper
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false